(()=>{
  'use strict';
  const api='../api/admin/agents/';
  const labels={coordination:'Coordinateur',satisfaction:'Satisfaction',commercial:'Commercial',developpement:'Développeur',tests:'Testeur',audiovisuel:'Audiovisuel',montage:'Monteur',web:'Web',marketing:'Marketing'};
  const positions={satisfaction:[18,16],commercial:[50,12],developpement:[82,16],tests:[13,50],coordination:[50,50],audiovisuel:[87,50],montage:[18,84],web:[50,88],marketing:[82,84]};
  let state={agents:Object.keys(labels),agentStatuses:{},dossiers:[],events:[],decisions:[],inputs:[],csrf:''};
  const $=selector=>document.querySelector(selector);
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const date=value=>value?new Date(value.replace(' ','T')+(value.includes('T')?'':'Z')).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'}):'—';
  const empty=text=>'<p class="empty">'+esc(text)+'</p>';

  function showView(name){document.querySelectorAll('.view').forEach(v=>{const active=v.id==='view-'+name;v.hidden=!active;v.classList.toggle('active',active)});document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));}
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));

  function lastEvent(agent){return state.events.find(e=>e.sourceAgent===agent||e.targetAgent===agent)}
  function renderNetwork(){
    const root=$('#agent-network'),center=positions.coordination;
    const lines=state.agents.filter(a=>a!=='coordination').map(agent=>{const p=positions[agent];const active=state.events.slice(0,12).some(e=>(e.sourceAgent===agent&&e.targetAgent==='coordination')||(e.targetAgent===agent&&e.sourceAgent==='coordination'));return '<line class="'+(active?'active':'')+'" x1="'+center[0]+'" y1="'+center[1]+'" x2="'+p[0]+'" y2="'+p[1]+'"/>'}).join('');
    root.innerHTML='<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">'+lines+'</svg>'+state.agents.map(agent=>{const p=positions[agent],event=lastEvent(agent),status=state.agentStatuses?.[agent]||'available',isActive=status==='active';return '<button type="button" class="agent-node '+agent+' '+(isActive?'active-now':'idle')+'" data-agent="'+agent+'" style="left:'+p[0]+'%;top:'+p[1]+'%"><strong>'+labels[agent]+'</strong><small>'+esc(status==='active'?'En cours':status==='blocked'?'Bloqué':event?'Disponible':'En attente')+'</small></button>'}).join('');
    root.querySelectorAll('[data-agent]').forEach(button=>button.addEventListener('click',()=>{root.querySelectorAll('.agent-node').forEach(n=>n.classList.remove('active'));button.classList.add('active');const event=lastEvent(button.dataset.agent);$('#agent-detail').innerHTML='<strong>'+labels[button.dataset.agent]+' :</strong> '+(event?esc(event.summary)+' · '+date(event.createdAt):'aucune activité enregistrée.')}));
  }
  function decisionCard(d,full=false){return '<article class="'+(full?'decision-full':'decision-card')+'"><h'+(full?'2':'3')+'>'+esc(d.id)+' · '+esc(d.question)+'</h'+(full?'2':'3')+'><p>'+esc(d.whyNow||d.blockedWork||'Décision transmise par le Coordinateur.')+'</p>'+(full?'<div class="decision-meta"><span class="badge '+esc(d.urgency)+'">'+esc(d.urgency)+'</span><span class="badge">'+esc(labels[d.requesterAgent]||d.requesterAgent)+'</span>'+(d.deadline?'<span class="badge">Échéance '+date(d.deadline)+'</span>':'')+'</div><p><strong>Recommandation :</strong> '+esc(d.recommendation||'Aucune')+'</p>':'')+'<button type="button" data-decide="'+esc(d.id)+'">Décider</button></article>'}
  function eventItem(e){return '<div class="timeline-item '+(e.eventType==='decision'?'decision':'')+'"><span class="timeline-dot"></span><div><strong>'+esc(labels[e.sourceAgent]||e.sourceAgent)+' → '+esc(labels[e.targetAgent]||e.targetAgent||'Dossier')+'</strong><small>'+esc(e.summary)+' · '+date(e.createdAt)+'</small></div></div>'}
  function eventDetails(e){const p=e.payload;if(!p||typeof p!=='object')return '';const deliverables=Array.isArray(p.livrables)?p.livrables.join(', '):'';return '<small>Statut : '+esc(p.statut||'—')+' · Livrables : '+esc(deliverables||'—')+' · Décision liée : '+esc(p.decisionLiee||'—')+' · Prochaine action : '+esc(p.prochaineAction||'—')+'</small>'}
  function bindDecisionButtons(){document.querySelectorAll('[data-decide]').forEach(b=>b.addEventListener('click',()=>openDecision(b.dataset.decide)))}
  function render(){
    const pending=state.decisions.filter(d=>d.status==='pending'),pendingInputs=(state.inputs||[]).filter(i=>i.status==='pending'),dayAgo=Date.now()-86400000,activeAgents=state.agents.filter(a=>a!=='coordination'&&state.agentStatuses?.[a]==='active').length;
    $('#metric-agents').textContent=activeAgents+' / 8';$('#metric-events').textContent=state.events.filter(e=>new Date(e.createdAt.replace(' ','T')+'Z').getTime()>dayAgo).length;$('#metric-decisions').textContent=pending.length;$('#metric-inputs').textContent=pendingInputs.length;$('#nav-decisions').textContent=pending.length;$('#nav-entrees').textContent=pendingInputs.length;$('#nav-dossiers').textContent=state.dossiers.filter(d=>d.status!=='closed').length;
    renderNetwork();
    $('#decision-preview').innerHTML=pending.length?pending.slice(0,3).map(d=>decisionCard(d)).join(''):empty('Aucune décision en attente.');
    $('#event-preview').innerHTML=state.events.length?state.events.slice(0,5).map(eventItem).join(''):empty('Aucun échange enregistré.');
    $('#dossier-list').innerHTML=state.dossiers.length?state.dossiers.map(d=>'<article class="dossier"><span class="badge '+esc(d.status)+'">'+esc(d.status)+'</span><h3>'+esc(d.id)+' · '+esc(d.title)+'</h3><p>'+esc(d.client||'Interne')+(d.version?' · '+esc(d.version):'')+'</p><p>Agent actuel : <strong>'+esc(labels[d.currentAgent]||d.currentAgent||'Coordinateur')+'</strong></p><p>Mis à jour : '+date(d.updatedAt)+'</p></article>').join(''):empty('Aucun dossier enregistré.');
    $('#input-body').innerHTML=(state.inputs||[]).length?state.inputs.map(i=>'<tr><td>'+date(i.createdAt)+'</td><td>'+esc(i.source)+'</td><td><strong>'+esc(i.title)+'</strong><small>'+esc(i.summary)+'</small></td><td><span class="badge '+esc(i.priority)+'">'+esc(i.priority)+'</span></td><td>'+esc(i.status)+'</td><td>'+esc(i.dossierId||'—')+'</td></tr>').join(''):'<tr><td colspan="6">Aucune demande enregistrée.</td></tr>';
    $('#decision-list').innerHTML=pending.length?pending.map(d=>decisionCard(d,true)).join(''):empty('Aucune décision ne requiert votre intervention.');
    $('#journal-body').innerHTML=state.events.length?state.events.map(e=>'<tr><td>'+date(e.createdAt)+'</td><td>'+esc(e.dossierId||'—')+'</td><td>'+esc(labels[e.sourceAgent]||e.sourceAgent)+'</td><td>'+esc(labels[e.targetAgent]||e.targetAgent||'—')+'</td><td>'+esc(e.summary)+eventDetails(e)+'</td></tr>').join(''):'<tr><td colspan="5">Aucune transmission enregistrée.</td></tr>';
    bindDecisionButtons();
  }
  async function load(){
    $('#alert').hidden=true;$('#sync-status').textContent='Synchronisation…';
    try{const response=await fetch(api,{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}});const data=await response.json().catch(()=>({}));if(response.status===401){location.replace('../compte/?session=expired');return}if(!response.ok)throw new Error(data.message||'Impossible de charger le cockpit.');state=data;$('#viewer').textContent=data.viewer.name;$('#sync-status').textContent='Coordinateur synchronisé · '+new Date(data.generatedAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});render()}catch(error){$('#sync-status').textContent='Synchronisation interrompue';$('#alert').textContent=error.message;$('#alert').hidden=false}
  }
  function openDecision(id){const d=state.decisions.find(item=>item.id===id);if(!d)return;const dialog=$('#decision-dialog');dialog.dataset.id=id;$('#decision-dialog-title').textContent=d.question;$('#decision-context').innerHTML='<p>'+esc(d.whyNow||'')+'</p>'+(d.recommendation?'<p><strong>Recommandation du Coordinateur :</strong> '+esc(d.recommendation)+'</p>':'');$('#decision-options').innerHTML=d.options.map((option,index)=>'<label class="option"><input type="radio" name="choice" value="'+esc(option)+'" '+(index===0?'required':'')+'><span>'+esc(option)+'</span></label>').join('');$('#decision-note').value='';$('#decision-message').textContent='';dialog.showModal()}
  document.querySelectorAll('.close').forEach(b=>b.addEventListener('click',()=>$('#decision-dialog').close()));
  $('#decision-form').addEventListener('submit',async event=>{event.preventDefault();const choice=new FormData(event.currentTarget).get('choice');if(!choice)return;const button=event.currentTarget.querySelector('[type=submit]');button.disabled=true;$('#decision-message').textContent='Enregistrement…';try{const response=await fetch(api,{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-Token':state.csrf},body:JSON.stringify({action:'resolve_decision',decisionId:$('#decision-dialog').dataset.id,choice,note:$('#decision-note').value})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Impossible d’enregistrer la décision.');$('#decision-dialog').close();await load()}catch(error){$('#decision-message').textContent=error.message}finally{button.disabled=false}});
  $('#input-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('[type=submit]');button.disabled=true;$('#input-message').textContent='Enregistrement…';try{const response=await fetch(api,{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-Token':state.csrf},body:JSON.stringify({action:'create_input',source:'cockpit',title:$('#input-title').value,summary:$('#input-summary').value,priority:$('#input-priority').value})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Impossible d’enregistrer la demande.');event.currentTarget.reset();$('#input-message').textContent='Demande ajoutée à la file.';await load()}catch(error){$('#input-message').textContent=error.message}finally{button.disabled=false}});
  $('#refresh').addEventListener('click',load);
  load();setInterval(load,60000);
})();
